### ISSUE TITLE
Delaying Seekbar on Music Widget

### ISSUE THREAD

**Issue by ardumpl** [amhndu/conky-cards#2]
Hi, dude... i just tested your conky widget, that was great. But, i noticed delayed process on musicinfo widget. It's taking few seconds to refresing progress bar. How i solve this problem?

**Comment by amhndu** [comment]
Hi!
You can adjust the update interval in the config: <https://github.com/amhndu/conky-cards/blob/master/mediaplayer_rc#L6>
It's defaulted to 2 seconds here, you can reduce it.

**Comment by ardumpl** [comment]
Thanks, dude i will check it ...
