### ISSUE TITLE
Length doesn't Showed Correctly

### ISSUE THREAD

**Issue by ardumpl** [amhndu/conky-cards#3]
I just found other bugs
When I playing media files with 40 min - above 60 min length, music widget doesn't showed correctly. Otherwise, it's nothing problem appeared. Here for screenshots

Figure (1)
![cuplikan layar_2019-01-18_22-04-41](https://user-images.githubusercontent.com/31944935/51392223-f4409c80-1b66-11e9-8c2a-0227f1c2a03d.png)

Figure (2)
![cuplikan layar_2019-01-19_04-15-09](https://user-images.githubusercontent.com/31944935/51392226-f4409c80-1b66-11e9-8926-2020be30c072.png)

**Comment by amhndu** [comment]
Sorry about the delay, I've been preoccupied.
Try with this new file: https://github.com/amhndu/conky-cards/blob/master/mediaplayer.py
I've also closed your previous issue, assuming it has been fixed.

**Comment by ardumpl** [comment]
Okay, I pick it.
